-- MySQL Script generated by MySQL Workbench
-- Thu Dec 21 16:56:48 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sisloja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `pos_servicetype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_servicetype` ;

CREATE TABLE IF NOT EXISTS `pos_servicetype` (
  `servicetype_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `service_cost` DOUBLE NULL,
  `comment` VARCHAR(100) NULL,
  PRIMARY KEY (`servicetype_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pos_people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_people` ;

CREATE TABLE IF NOT EXISTS `pos_people` (
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `address_1` VARCHAR(255) NOT NULL,
  `address_2` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `state` VARCHAR(255) NOT NULL,
  `zip` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  `comments` TEXT NOT NULL,
  `person_id` INT(10) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_customers` ;

CREATE TABLE IF NOT EXISTS `pos_customers` (
  `person_id` INT(10) NOT NULL,
  `account_number` VARCHAR(255) NULL DEFAULT NULL,
  `taxable` INT(1) NOT NULL DEFAULT '1',
  `deleted` INT(1) NOT NULL DEFAULT '0',
  UNIQUE INDEX `account_number` (`account_number` ASC),
  INDEX `person_id` (`person_id` ASC),
  CONSTRAINT `pos_customers_ibfk_1`
    FOREIGN KEY (`person_id`)
    REFERENCES `pos_people` (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_service` ;

CREATE TABLE IF NOT EXISTS `pos_service` (
  `service_id` INT(10) NOT NULL,
  `servicetype_id` INT(10) NOT NULL,
  `person_id` INT(10) NULL,
  `start_time` TIMESTAMP NULL,
  `finish_time` TIMESTAMP NULL,
  PRIMARY KEY (`service_id`),
  INDEX `fk_service_servicetype1_idx` (`servicetype_id` ASC),
  INDEX `fk_service_customer_idx` (`person_id` ASC),
  CONSTRAINT `fk_service_servicetypr1`
    FOREIGN KEY (`servicetype_id`)
    REFERENCES `pos_servicetype` (`servicetype_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_customer`
    FOREIGN KEY (`person_id`)
    REFERENCES `sisloja`.`pos_customers` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pos_employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_employees` ;

CREATE TABLE IF NOT EXISTS `pos_employees` (
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `person_id` INT(10) NOT NULL,
  `deleted` INT(1) NOT NULL DEFAULT '0',
  UNIQUE INDEX `username` (`username` ASC),
  INDEX `person_id` (`person_id` ASC),
  CONSTRAINT `pos_employees_ibfk_1`
    FOREIGN KEY (`person_id`)
    REFERENCES `pos_people` (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_doservice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_doservice` ;

CREATE TABLE IF NOT EXISTS `pos_doservice` (
  `sevice_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`sevice_id`, `person_id`),
  INDEX `fk_doservice_service_idx` (`sevice_id` ASC),
  INDEX `fk_doservice_person_id_idx` (`person_id` ASC),
  CONSTRAINT `fk_doservice_service_id`
    FOREIGN KEY (`sevice_id`)
    REFERENCES `pos_service` (`service_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doservice_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `sisloja`.`pos_employees` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pos_suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_suppliers` ;

CREATE TABLE IF NOT EXISTS `pos_suppliers` (
  `person_id` INT(10) NOT NULL,
  `company_name` VARCHAR(255) NOT NULL,
  `account_number` VARCHAR(255) NULL DEFAULT NULL,
  `deleted` INT(1) NOT NULL DEFAULT '0',
  UNIQUE INDEX `account_number` (`account_number` ASC),
  INDEX `person_id` (`person_id` ASC),
  CONSTRAINT `pos_suppliers_ibfk_1`
    FOREIGN KEY (`person_id`)
    REFERENCES `pos_people` (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_items` ;

CREATE TABLE IF NOT EXISTS `pos_items` (
  `name` VARCHAR(255) NOT NULL,
  `category` VARCHAR(255) NOT NULL,
  `supplier_id` INT(11) NULL DEFAULT NULL,
  `item_number` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NOT NULL,
  `cost_price` DOUBLE(15,2) NOT NULL,
  `unit_price` DOUBLE(15,2) NOT NULL,
  `quantity` DOUBLE(15,2) NOT NULL DEFAULT '0.00',
  `reorder_level` DOUBLE(15,2) NOT NULL DEFAULT '0.00',
  `location` VARCHAR(255) NOT NULL,
  `item_id` INT(10) NOT NULL AUTO_INCREMENT,
  `allow_alt_description` TINYINT(1) NOT NULL,
  `is_serialized` TINYINT(1) NOT NULL,
  `deleted` INT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `item_number` (`item_number` ASC),
  INDEX `ospos_items_ibfk_1` (`supplier_id` ASC),
  CONSTRAINT `pos_items_ibfk_1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `pos_suppliers` (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_service_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_service_items` ;

CREATE TABLE IF NOT EXISTS `pos_service_items` (
  `service_id` INT(10) NOT NULL,
  `item_id` INT(10) NOT NULL,
  PRIMARY KEY (`service_id`, `item_id`),
  INDEX `fk_service_items_serviceidx` (`service_id` ASC),
  INDEX `fk_service_items_itemid_idx` (`item_id` ASC),
  CONSTRAINT `fk_service_items_serviceid`
    FOREIGN KEY (`service_id`)
    REFERENCES `pos_service` (`service_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_items_itemid`
    FOREIGN KEY (`item_id`)
    REFERENCES `sisloja`.`pos_items` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pos_app_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_app_config` ;

CREATE TABLE IF NOT EXISTS `pos_app_config` (
  `key` VARCHAR(255) NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`key`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_giftcards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_giftcards` ;

CREATE TABLE IF NOT EXISTS `pos_giftcards` (
  `giftcard_id` INT(11) NOT NULL AUTO_INCREMENT,
  `giftcard_number` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `value` DOUBLE(15,2) NOT NULL,
  `deleted` INT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`giftcard_id`),
  UNIQUE INDEX `giftcard_number` (`giftcard_number` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `pos_inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_inventory` ;

CREATE TABLE IF NOT EXISTS `pos_inventory` (
  `trans_id` INT(11) NOT NULL AUTO_INCREMENT,
  `trans_items` INT(11) NOT NULL DEFAULT '0',
  `trans_user` INT(11) NOT NULL DEFAULT '0',
  `trans_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `trans_comment` TEXT NOT NULL,
  `trans_inventory` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`trans_id`),
  INDEX `ospos_inventory_ibfk_1` (`trans_items` ASC),
  INDEX `ospos_inventory_ibfk_2` (`trans_user` ASC),
  CONSTRAINT `pos_inventory_ibfk_1`
    FOREIGN KEY (`trans_items`)
    REFERENCES `pos_items` (`item_id`),
  CONSTRAINT `pos_inventory_ibfk_2`
    FOREIGN KEY (`trans_user`)
    REFERENCES `pos_employees` (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_item_kits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_item_kits` ;

CREATE TABLE IF NOT EXISTS `pos_item_kits` (
  `item_kit_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`item_kit_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_item_kit_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_item_kit_items` ;

CREATE TABLE IF NOT EXISTS `pos_item_kit_items` (
  `item_kit_id` INT(11) NOT NULL,
  `item_id` INT(11) NOT NULL,
  `quantity` DOUBLE(15,2) NOT NULL,
  PRIMARY KEY (`item_kit_id`, `item_id`, `quantity`),
  INDEX `ospos_item_kit_items_ibfk_2` (`item_id` ASC),
  CONSTRAINT `pos_item_kit_items_ibfk_1`
    FOREIGN KEY (`item_kit_id`)
    REFERENCES `pos_item_kits` (`item_kit_id`)
    ON DELETE CASCADE,
  CONSTRAINT `pos_item_kit_items_ibfk_2`
    FOREIGN KEY (`item_id`)
    REFERENCES `pos_items` (`item_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_items_taxes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_items_taxes` ;

CREATE TABLE IF NOT EXISTS `pos_items_taxes` (
  `item_id` INT(10) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `percent` DOUBLE(15,3) NOT NULL,
  PRIMARY KEY (`item_id`, `name`, `percent`),
  CONSTRAINT `pos_items_taxes_ibfk_1`
    FOREIGN KEY (`item_id`)
    REFERENCES `pos_items` (`item_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_modules` ;

CREATE TABLE IF NOT EXISTS `pos_modules` (
  `name_lang_key` VARCHAR(255) NOT NULL,
  `desc_lang_key` VARCHAR(255) NOT NULL,
  `sort` INT(10) NOT NULL,
  `module_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`module_id`),
  UNIQUE INDEX `desc_lang_key` (`desc_lang_key` ASC),
  UNIQUE INDEX `name_lang_key` (`name_lang_key` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_permissions` ;

CREATE TABLE IF NOT EXISTS `pos_permissions` (
  `module_id` VARCHAR(255) NOT NULL,
  `person_id` INT(10) NOT NULL,
  PRIMARY KEY (`module_id`, `person_id`),
  INDEX `person_id` (`person_id` ASC),
  CONSTRAINT `pos_permissions_ibfk_1`
    FOREIGN KEY (`person_id`)
    REFERENCES `pos_employees` (`person_id`),
  CONSTRAINT `pos_permissions_ibfk_2`
    FOREIGN KEY (`module_id`)
    REFERENCES `pos_modules` (`module_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_receivings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_receivings` ;

CREATE TABLE IF NOT EXISTS `pos_receivings` (
  `receiving_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `supplier_id` INT(10) NULL DEFAULT NULL,
  `employee_id` INT(10) NOT NULL DEFAULT '0',
  `comment` TEXT NOT NULL,
  `receiving_id` INT(10) NOT NULL AUTO_INCREMENT,
  `payment_type` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`receiving_id`),
  INDEX `supplier_id` (`supplier_id` ASC),
  INDEX `employee_id` (`employee_id` ASC),
  CONSTRAINT `pos_receivings_ibfk_1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `pos_employees` (`person_id`),
  CONSTRAINT `pos_receivings_ibfk_2`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `pos_suppliers` (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_receivings_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_receivings_items` ;

CREATE TABLE IF NOT EXISTS `pos_receivings_items` (
  `receiving_id` INT(10) NOT NULL DEFAULT '0',
  `item_id` INT(10) NOT NULL DEFAULT '0',
  `description` VARCHAR(30) NULL DEFAULT NULL,
  `serialnumber` VARCHAR(30) NULL DEFAULT NULL,
  `line` INT(3) NOT NULL,
  `quantity_purchased` INT(10) NOT NULL DEFAULT '0',
  `item_cost_price` DECIMAL(15,2) NOT NULL,
  `item_unit_price` DOUBLE(15,2) NOT NULL,
  `discount_percent` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`receiving_id`, `item_id`, `line`),
  INDEX `item_id` (`item_id` ASC),
  CONSTRAINT `pos_receivings_items_ibfk_1`
    FOREIGN KEY (`item_id`)
    REFERENCES `pos_items` (`item_id`),
  CONSTRAINT `pos_receivings_items_ibfk_2`
    FOREIGN KEY (`receiving_id`)
    REFERENCES `pos_receivings` (`receiving_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_sales` ;

CREATE TABLE IF NOT EXISTS `pos_sales` (
  `sale_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `customer_id` INT(10) NULL DEFAULT NULL,
  `employee_id` INT(10) NOT NULL DEFAULT '0',
  `comment` TEXT NOT NULL,
  `sale_id` INT(10) NOT NULL AUTO_INCREMENT,
  `payment_type` VARCHAR(512) NULL DEFAULT NULL,
  PRIMARY KEY (`sale_id`),
  INDEX `customer_id` (`customer_id` ASC),
  INDEX `employee_id` (`employee_id` ASC),
  CONSTRAINT `pos_sales_ibfk_1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `pos_employees` (`person_id`),
  CONSTRAINT `pos_sales_ibfk_2`
    FOREIGN KEY (`customer_id`)
    REFERENCES `pos_customers` (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_sales_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_sales_items` ;

CREATE TABLE IF NOT EXISTS `pos_sales_items` (
  `sale_id` INT(10) NOT NULL DEFAULT '0',
  `item_id` INT(10) NOT NULL DEFAULT '0',
  `description` VARCHAR(30) NULL DEFAULT NULL,
  `serialnumber` VARCHAR(30) NULL DEFAULT NULL,
  `line` INT(3) NOT NULL DEFAULT '0',
  `quantity_purchased` DOUBLE(15,2) NOT NULL DEFAULT '0.00',
  `item_cost_price` DECIMAL(15,2) NOT NULL,
  `item_unit_price` DOUBLE(15,2) NOT NULL,
  `discount_percent` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`sale_id`, `item_id`, `line`),
  INDEX `item_id` (`item_id` ASC),
  CONSTRAINT `pos_sales_items_ibfk_1`
    FOREIGN KEY (`item_id`)
    REFERENCES `pos_items` (`item_id`),
  CONSTRAINT `pos_sales_items_ibfk_2`
    FOREIGN KEY (`sale_id`)
    REFERENCES `pos_sales` (`sale_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_sales_items_taxes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_sales_items_taxes` ;

CREATE TABLE IF NOT EXISTS `pos_sales_items_taxes` (
  `sale_id` INT(10) NOT NULL,
  `item_id` INT(10) NOT NULL,
  `line` INT(3) NOT NULL DEFAULT '0',
  `name` VARCHAR(255) NOT NULL,
  `percent` DOUBLE(15,3) NOT NULL,
  PRIMARY KEY (`sale_id`, `item_id`, `line`, `name`, `percent`),
  INDEX `item_id` (`item_id` ASC),
  CONSTRAINT `pos_sales_items_taxes_ibfk_1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `pos_sales_items` (`sale_id`),
  CONSTRAINT `pos_sales_items_taxes_ibfk_2`
    FOREIGN KEY (`item_id`)
    REFERENCES `pos_items` (`item_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_sales_payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_sales_payments` ;

CREATE TABLE IF NOT EXISTS `pos_sales_payments` (
  `sale_id` INT(10) NOT NULL,
  `payment_type` VARCHAR(40) NOT NULL,
  `payment_amount` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`sale_id`, `payment_type`),
  CONSTRAINT `pos_sales_payments_ibfk_1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `pos_sales` (`sale_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_sales_suspended`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_sales_suspended` ;

CREATE TABLE IF NOT EXISTS `pos_sales_suspended` (
  `sale_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `customer_id` INT(10) NULL DEFAULT NULL,
  `employee_id` INT(10) NOT NULL DEFAULT '0',
  `comment` TEXT NOT NULL,
  `sale_id` INT(10) NOT NULL AUTO_INCREMENT,
  `payment_type` VARCHAR(512) NULL DEFAULT NULL,
  PRIMARY KEY (`sale_id`),
  INDEX `customer_id` (`customer_id` ASC),
  INDEX `employee_id` (`employee_id` ASC),
  CONSTRAINT `pos_sales_suspended_ibfk_1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `pos_employees` (`person_id`),
  CONSTRAINT `pos_sales_suspended_ibfk_2`
    FOREIGN KEY (`customer_id`)
    REFERENCES `pos_customers` (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_sales_suspended_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_sales_suspended_items` ;

CREATE TABLE IF NOT EXISTS `pos_sales_suspended_items` (
  `sale_id` INT(10) NOT NULL DEFAULT '0',
  `item_id` INT(10) NOT NULL DEFAULT '0',
  `description` VARCHAR(30) NULL DEFAULT NULL,
  `serialnumber` VARCHAR(30) NULL DEFAULT NULL,
  `line` INT(3) NOT NULL DEFAULT '0',
  `quantity_purchased` DOUBLE(15,2) NOT NULL DEFAULT '0.00',
  `item_cost_price` DECIMAL(15,2) NOT NULL,
  `item_unit_price` DOUBLE(15,2) NOT NULL,
  `discount_percent` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`sale_id`, `item_id`, `line`),
  INDEX `item_id` (`item_id` ASC),
  CONSTRAINT `pos_sales_suspended_items_ibfk_1`
    FOREIGN KEY (`item_id`)
    REFERENCES `pos_items` (`item_id`),
  CONSTRAINT `pos_sales_suspended_items_ibfk_2`
    FOREIGN KEY (`sale_id`)
    REFERENCES `pos_sales_suspended` (`sale_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_sales_suspended_items_taxes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_sales_suspended_items_taxes` ;

CREATE TABLE IF NOT EXISTS `pos_sales_suspended_items_taxes` (
  `sale_id` INT(10) NOT NULL,
  `item_id` INT(10) NOT NULL,
  `line` INT(3) NOT NULL DEFAULT '0',
  `name` VARCHAR(255) NOT NULL,
  `percent` DOUBLE(15,3) NOT NULL,
  PRIMARY KEY (`sale_id`, `item_id`, `line`, `name`, `percent`),
  INDEX `item_id` (`item_id` ASC),
  CONSTRAINT `pos_sales_suspended_items_taxes_ibfk_1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `pos_sales_suspended_items` (`sale_id`),
  CONSTRAINT `pos_sales_suspended_items_taxes_ibfk_2`
    FOREIGN KEY (`item_id`)
    REFERENCES `pos_items` (`item_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_sales_suspended_payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_sales_suspended_payments` ;

CREATE TABLE IF NOT EXISTS `pos_sales_suspended_payments` (
  `sale_id` INT(10) NOT NULL,
  `payment_type` VARCHAR(40) NOT NULL,
  `payment_amount` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`sale_id`, `payment_type`),
  CONSTRAINT `pos_sales_suspended_payments_ibfk_1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `pos_sales_suspended` (`sale_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pos_sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pos_sessions` ;

CREATE TABLE IF NOT EXISTS `pos_sessions` (
  `id` VARCHAR(40) NOT NULL DEFAULT '0',
  `ip_address` VARCHAR(16) NOT NULL DEFAULT '0',
  `user_agent` VARCHAR(120) NOT NULL,
  `timestamp` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `data` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
